#!/usr/bin/env bash

export CONTECO_LABEL="filebeat.file - ContEco"
export CONTECO_DESCRIPTION="Filebeat image with file input, with templated default configuration."

export CONTECO_TYPE="filebeat"
export CONTECO_NAME="file"
export CONTECO_TAG="7.8.0"

export CONTECO_BASE="external.filebeat:7.8.0"
export CONTECO_BUILD="image-base"
