#!/usr/bin/env bash

export CONTECO_LABEL="Conteco filebeat base"
export CONTECO_DESCRIPTION="The ElasticSearch Filebeat base image."

export CONTECO_TYPE="filebeat"
export CONTECO_NAME="base"
export CONTECO_TAG="6.6.2"

export CONTECO_BASE="external.filebeat:6.6.2"
export CONTECO_BUILD="image-base"
