#!/usr/bin/env bash

export CONTECO_LABEL="filebeat.file - ContEco"
export CONTECO_DESCRIPTION="ElasticSearch Filebeat image configured for file input, with templated default configuration."

export CONTECO_TYPE="filebeat"
export CONTECO_NAME="file"
export CONTECO_TAG="7.9.2"

export CONTECO_BASE="external.filebeat:7.9.2"
export CONTECO_BUILD="image-base"
